language: python
env:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

notifications:
  email: false

before_install:
  - python --version
  - pip install -U pip

install:
  - python setup.py install
  - pip install -r docs/doc_requirements.txt

script:
  - pytest --cov=pubmed_parser tests/ --verbose
  - cd docs && make html
  - touch _build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  local_dir: docs/_build/html/


after_success:
  - bash <(curl -s https://codecov.io/bash)